### ISSUE TITLE
0.7.0 availability on Maven Central

### ISSUE THREAD

**Issue by xela85** [eikek/sbt-openapi-schema#44]
Hello eikek, 

In order to use the new features of _sbt-openapi-schema_, I need the 0.7.0 to be released in Maven central (or in any sbt plugin repository). 

I have seen that this version has been released in Git, however it seems to be missing in Sonatype. 
Could you please push it to Maven Central ? 

Thanks in advance

**Comment by eikek** [comment]
Hi @xela85 , oh thanks for notifying. I thought it is already on maven central, as I use the sbt-sonatype plugin that usually deploys it to maven central automatically. Something went wrong there.

**Comment by eikek** [comment]
Should be there in some minutes
