### ISSUE TITLE
Could not find lazy implicit value of type DerivedDecoder/DerivedAsObjectEncoder

### ISSUE THREAD

**Issue by danellis** [eikek/sbt-openapi-schema#46]
I'm using an OpenAPI 3 YAML file from eBay to generate Scala code. All the case classes seem to get generated just fine, but when I added JSON, it get the following errors on 2 out of 67 files:

```
[error] /Users/dan/projects/wolfbone/cloud/services/ebay/target/scala-2.13/src_managed/main/work/wolfbone/ebay/fulfillment/OrderSearchPagedCollection.scala:12:80: could not find Lazy implicit value of type io.circe.generic.decoding.DerivedDecoder[work.wolfbone.ebay.fulfillment.OrderSearchPagedCollection]
[error]   implicit val jsonDecoder: Decoder[OrderSearchPagedCollection] = deriveDecoder[OrderSearchPagedCollection]
[error]                                                                                ^
[error] /Users/dan/projects/wolfbone/cloud/services/ebay/target/scala-2.13/src_managed/main/work/wolfbone/ebay/fulfillment/OrderSearchPagedCollection.scala:13:80: could not find Lazy implicit value of type io.circe.generic.encoding.DerivedAsObjectEncoder[work.wolfbone.ebay.fulfillment.OrderSearchPagedCollection]
[error]   implicit val jsonEncoder: Encoder[OrderSearchPagedCollection] = deriveEncoder[OrderSearchPagedCollection]
[error]                                                                                ^
[error] /Users/dan/projects/wolfbone/cloud/services/ebay/target/scala-2.13/src_managed/main/work/wolfbone/ebay/fulfillment/ShippingFulfillmentPagedCollection.scala:12:88: could not find Lazy implicit value of type io.circe.generic.decoding.DerivedDecoder[work.wolfbone.ebay.fulfillment.ShippingFulfillmentPagedCollection]
[error]   implicit val jsonDecoder: Decoder[ShippingFulfillmentPagedCollection] = deriveDecoder[ShippingFulfillmentPagedCollection]
[error]                                                                                        ^
[error] /Users/dan/projects/wolfbone/cloud/services/ebay/target/scala-2.13/src_managed/main/work/wolfbone/ebay/fulfillment/ShippingFulfillmentPagedCollection.scala:13:88: could not find Lazy implicit value of type io.circe.generic.encoding.DerivedAsObjectEncoder[work.wolfbone.ebay.fulfillment.ShippingFulfillmentPagedCollection]
[error]   implicit val jsonEncoder: Encoder[ShippingFulfillmentPagedCollection] = deriveEncoder[ShippingFulfillmentPagedCollection]
```

I'm not sure what's happening here. I assume it's complaining that it does have a decoder and encoder for the nested types, but there are several other types with nested types, so I don't know what's special about these. I've attached the two files and a copy of the spec.

[sell_fulfillment_v1_oas3.yaml](https://github.com/eikek/sbt-openapi-schema/files/5462562/sell_fulfillment_v1_oas3.yaml.txt)
[OrderSearchPagedCollection.scala](https://github.com/eikek/sbt-openapi-schema/files/5462551/OrderSearchPagedCollection.scala.txt)
[ShippingFulfillmentPagedCollection.scala](https://github.com/eikek/sbt-openapi-schema/files/5462554/ShippingFulfillmentPagedCollection.scala.txt)

**Comment by danellis** [comment]
I found the error. Those two class both have a field of type `List[Error]`, which was resolving as Circe's `Error` class. I added a custom mapping from `List[Error]` to `List[work.wolfbone.ebay.fulfillment.Error]`. 

The generated files are using wildcard imports:
```scala
import io.circe._
import io.circe.generic.semiauto._
```

which brings a lot into scope. Perhaps you could do the following instead?

```scala
object ShippingFulfillmentPagedCollection {
  implicit val jsonDecoder: io.circe.Decoder[ShippingFulfillmentPagedCollection] = io.circe.generic.semiauto.deriveDecoder[ShippingFulfillmentPagedCollection]
  implicit val jsonEncoder: io.circe.Encoder[ShippingFulfillmentPagedCollection] = io.circe.generic.semiauto.deriveEncoder[ShippingFulfillmentPagedCollection]
}
```

It's not code that anyone will be working with, so it doesn't matter if it's a bit more verbose to give some extra safety.

**Comment by eikek** [comment]
Hi @danellis , thanks for reporting (and finding the cause!). Yes, of course that's much better for generated code. There shouldn't be wildcard imports.
